# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160223235143 on 2016-04-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='friends',
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='followers',
            field=models.ManyToManyField(related_name='follower_of', to='imager_profile.ImagerProfile'),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='region',
            field=models.CharField(choices=[('pnw', 'Pacific Northwest'), ('ne', 'New England'), ('ma', 'Mid-Atlantic'), ('se', 'Southeast'), ('mw', 'Midwest'), ('ds', 'Deep South'), ('sw', 'Southwest'), ('cf', 'California'), ('ak', 'Alaska'), ('hi', 'Hawaii')], max_length=30),
        ),
    ]
