# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160223235143 on 2016-04-13 00:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=255)),
                ('album_description', models.TextField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('advertising', 'Advertising'), ('architecture', 'Architecture'), ('book', 'Book'), ('deeper perspective', 'Deeper Perspective'), ('editorial', 'Editorial'), ('event', 'Event'), ('fine art', 'Fine Art'), ('moving images', 'Moving Images'), ('nature', 'Nature'), ('people', 'People'), ('special', 'Special')], max_length=128)),
                ('image', models.ImageField(upload_to=b'')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('shared', 'Shared')], max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_albums', to='imager_images.Photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL),
        ),
    ]
